### ISSUE TITLE
Does not display error messages

### ISSUE THREAD

**Issue by vlamai** [christianhelle/httpgenerator#78]
**Describe the bug**
if error contains hash tag it doesn't print error message 

`The path signature '/api/v{}/specifications/{}' MUST be unique. [#/paths//api/v{version}/specifications/{specificationId}]`

```cs
System.InvalidOperationException: Invalid hex color '#/paths//api/v{version}/specifications/{specificationId}'.
   at Spectre.Console.StyleParser.Parse(String text) in /_/src/Spectre.Console/StyleParser.cs:line 10
   at Spectre.Console.MarkupParser.Parse(String text, Style style) in /_/src/Spectre.Console/Internal/Text/Markup/MarkupParser.cs:line 29
   at Spectre.Console.AnsiConsoleExtensions.Markup(IAnsiConsole console, String value) in /_/src/Spectre.Console/Extensions/AnsiConsoleExtensions.Markup.cs:line 77
   at Spectre.Console.AnsiConsoleExtensions.MarkupLine(IAnsiConsole console, String value) in /_/src/Spectre.Console/Extensions/AnsiConsoleExtensions.Markup.cs:line 117
   at Spectre.Console.AnsiConsole.MarkupLine(String value) in /_/src/Spectre.Console/AnsiConsole.Markup.cs:line 81
   at HttpGenerator.GenerateCommand.TryWriteLine(OpenApiError error, String color, String label) in \httpgenerator\src\HttpGenerator\GenerateCommand.cs:line 151
```

```cs
    private static void TryWriteLine(
        OpenApiError error,
        string color,
        string label)
    {
        try
        {
            AnsiConsole.MarkupLine($"[{color}]{label}:{Crlf}{error}{Crlf}[/]");
        }
        catch
        {
            //Console.WriteLine(error);
        }
    }
```

**Comment by christianhelle** [comment]
Thanks for taking the time to report this @vlamai
